### ISSUE TITLE
Problem starting Jitsi / AudioContext on page load

### ISSUE THREAD

**Issue by julianmichael** [fpw23/telimed#1]
Hi Frank, I stumbled onto this when researching how to use lib-jitsi-meet. You've done awesome work providing a MWE and sharing your findings.

I'm working on porting your example to Scala.js React, and I have my version mostly working but I'm running into a problem:
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```
Basically I can't grab ahold of the mic and start recording/playing audio on page load. This is particularly a problem because I think the AudioContext is being started when I initialize Jitsi, which I would like to do on page load.

Perhaps I could add some extra logic to get around this by reaching in and finding the audio context and telling it to resume or something. But I noticed [your example](https://fpw23.github.io/telimed/) doesn't have this problem, and I couldn't find anything in the code addressing it. Did you run into this issue? Did you do something to fix it?

Thanks!

**Comment by fpw23** [comment]
Hi Julian, Glad my demo helped you out!  The only big audio issue I found was not hooking the local track to a audio tag because it would give me echoing, that stumped me for a while.   I think you are going in the right direction based on the error, it sounds like the audio context is just not loaded.  I am waiting for ComponentDidMount because at that point I am ensured the browser has the page rendered and my DOM should be stable but it sounds like Scala.js React may lazy load stuff waiting on user gestures.   I have never worked with Scala.js before, is this mobile?  How does Scala take in libraries?  I had just load the jitsi library as a script tag and let it attach to the window and use it from there, is it the same thing in Scala?  I know under the covers jitsi is using navigator.mediadevices to get tracks.  Can you do the same directly in your code and see if you get this error still, if so you can take jitsi out of the loop and focus on just solving why navigator.mediadevices is failing.   Let me know if that helps, Frank Sent from Mail for Windows 10 From: Julian MichaelSent: Thursday, July 2, 2020 10:05 PMTo: fpw23/telimedCc: SubscribedSubject: [fpw23/telimed] Problem starting Jitsi / AudioContext on page load (#1) Hi Frank, I stumbled onto this when researching how to use lib-jitsi-meet. You've done awesome work providing a MWE and sharing your findings.I'm working on porting your example to Scala.js React, and I have my version mostly working but I'm running into a problem:The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLuBasically I can't grab ahold of the mic and start recording/playing audio on page load. This is particularly a problem because I think the AudioContext is being started when I initialize Jitsi, which I would like to do on page load.Perhaps I could add some extra logic to get around this by reaching in and finding the audio context and telling it to resume or something. But I noticed your example doesn't have this problem, and I couldn't find anything in the code addressing it. Did you run into this issue? Did you do something to fix it?Thanks!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by julianmichael** [comment]
Thanks for your reply! As a bit of background, scala.js is just a way to compile Scala to JavaScript for use in webapps, and I'm running on desktop. But anyway, the logged warning does seem to have been an issue with how I was including lib-jitsi-meet onto the page. Instead of concatenating it with my other JS dependencies I stuck it in its own script tag in the header and I'm no longer seeing the warning. However, I'm still having issues with audio; neither do I get an echo when including the audio tag, nor does it send any sound through to the conference. It's clearly a different issue and I have to just keep debugging.

But, this issue is resolved I guess. Thanks again!

**Comment by julianmichael** [comment]
AHA! I found it! The problem was I mindlessly copied [this line](https://github.com/fpw23/telimed/blob/master/src/LocalTracks.js#L94). Perhaps you meant to leave it as `unmute()` there? If I delete it or change it to `unmute()` then things seem to work as expected.

**Comment by fpw23** [comment]
Hmm, if I remember correctly that was what caused my echo issues I was talking about but that's great if you got it to work without muting.  Sorry for the confusion it caused you.
